### ISSUE TITLE
Resolve "iFrame element has accessible name" feedback

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#435]
[iFrame element has accessible name](https://act-rules.github.io/rules/cae760)
This issue is to resolve comments from the [Survey results](https://www.w3.org/2002/09/wbs/93339/iFrameName/results) that ended on 19 Feb.

## Wilco Fiers
- [ ] Failed example 7 is only consistent in Alpha

## Kathy Eng
- [ ] Suggest adding an applicable example with tabindex=-1 to show that iframe is in accessibility tree and rule is applicable.
**Mary Jo commented** _I don't think it is necessary to have another example with tabindex=-1 as that is known to only remove an element from the tab order and doesn't remove its role or the requirement for an accessible name._
- [ ] https://act-rules.github.io/implementation/axe-core#id-cae760 has an extra column of results (maybe from a different test?).
**Mary Jo commented** _I think the additional Axe results is because there are 2 rules in Axe covering different aspects of the test cases (Wilco, please verify)._
- [ ] Failed Ex 3 and Inapplicable Ex 3 are untested for all implementors but Axe. Should we get these tested by them?
**Mary Jo commented** _I think we only need one implementation for publication, but we should definitely ask for the missing results._
- [ ] Accessibility support: Some browsers include iframe elements in the sequential focus navigation. Suggest edit to last sentence: This ensures that iframe elements can always be scrolled using the keyboard. 

Suggest edit to last sentence: This ensures that iframe elements can be scrolled and its content can be accessed by keyboard.

## Trevor Bostic
- [ ] Should we remove passed example 4 to be consistent with removing :-) from accessible names.across all rules?

## Jonathan Avila 
- [ ] I have an open [issue #1186](https://github.com/act-rules/act-rules.github.io/issues/1186) in github on whether iFrames with tabIndex -1 should really be exempt from the naming rule. While I agree they don't fit under SC 4.1.2 I believe it should fall under SC 1.3.1.

## Kasper Isager
- [ ] [Issue #1170](https://github.com/act-rules/act-rules.github.io/issues/1170) should be resolved before publication.  NOTE: This was reiterated by others' responses on the survey.

**Comment by WilcoFiers** [comment]
Heard the fixes for this is going into PR tomorrow, it'll need a final call. Once that's done this can be picked up again. @jkodu

**Comment by jkodu** [comment]
## Wilco Fiers
- [x]  Failed example 7 is only consistent in Alpha
> @jkodu comment: This rule does not have a failed example 7. The examples were modified in this [commit](https://github.com/act-rules/act-rules.github.io/commit/fdbf857bb5aed44c8a936cb222ee4d712ef474a6#diff-e5855eef878bfc5e2ac47f8ae6846dc4).

## Kathy Eng
 * [x]  Suggest adding an applicable example with tabindex=-1 to show that iframe is in accessibility tree and rule is applicable.

> **Mary Jo commented** _I don't think it is necessary to have another example with tabindex=-1 as that is known to only remove an element from the tab order and doesn't remove its role or the requirement for an accessible name._
> @jkodu comment: The [accessibility support note](https://act-rules.github.io/rules/cae760#accessibility-support) on the rule covers this neatly. There are a few examples surrounding tab index.

 * [x]  [act-rules.github.io/implementation/axe-core#id-cae760](https://act-rules.github.io/implementation/axe-core#id-cae760) has an extra column of results (maybe from a different test?).
> **Mary Jo commented** _I think the additional Axe results is because there are 2 rules in Axe covering different aspects of the test cases (Wilco, please verify)._
> @jkodu comment: Axe has a one -> many mapping when it comes to how many of the axe rules apply to a given ACT rule. Hence for many implementations it is normal to see multiple column of results from other rules/ checks from axe, but the one that applies for a given rule is the one with either consistent or partially consistent results. Hope that helps.

 * [x]  Failed Ex 3 and Inapplicable Ex 3 are untested for all implementors but Axe. Should we get these tested by them?
> **Mary Jo commented** _I think we only need one implementation for publication, but we should definitely ask for the missing results._
> @jkodu comment: Currently [sortsite](https://act-rules.github.io/implementation/sortsite#id-cae760), [alfa](https://act-rules.github.io/implementation/alfa#id-cae760) and [Axe](https://act-rules.github.io/implementation/axe-core#id-cae760) have results that are other than untested. I will email other implementers, to update the results.

 * [x]  Accessibility support: Some browsers include iframe elements in the sequential focus navigation. Suggest edit to last sentence: This ensures that iframe elements can always be scrolled using the keyboard.
> Suggest edit to last sentence: This ensures that iframe elements can be scrolled and its content can be accessed by keyboard.
> @jkodu comment: Updated 👌 
 
## Trevor Bostic
* [x]  Should we remove passed example 4 to be consistent with removing :-) from accessible names.across all rules?
> @jkodu comment: Removed 👌 - [commit](https://github.com/act-rules/act-rules.github.io/commit/4d1b6c8a3675fa3b7ca55fbaa45b1f4c601b0a37#diff-e5855eef878bfc5e2ac47f8ae6846dc4)

> ## Jonathan Avila
* [x]  I have an open [issue #1186](https://github.com/act-rules/act-rules.github.io/issues/1186) in github on whether iFrames with tabIndex -1 should really be exempt from the naming rule. While I agree they don't fit under SC 4.1.2 I believe it should fall under SC 1.3.1.
> @jkodu comment: This issue has been resolved with notes. See comments in issue.

> ## Kasper Isager
> * [x]  [Issue #1170](https://github.com/act-rules/act-rules.github.io/issues/1170) should be resolved before publication.  NOTE: This was reiterated by others' responses on the survey.
>@jkodu comment: addressed in PR - https://github.com/act-rules/act-rules.github.io/pull/1269

**Comment by jkodu** [comment]
@WilcoFiers this is back to the Task force for review

**Comment by jkodu** [comment]
## Pending comment to be resolved

## Kasper Isager

* [ ]  [Issue #1170](https://github.com/act-rules/act-rules.github.io/issues/1170) should be resolved before publication.  NOTE: This was reiterated by others' responses on the survey.

> @jkodu comment: addressed in PR - https://github.com/act-rules/act-rules.github.io/pull/1269 
> @jkodu  comment: Update -> The above PR was closed as recommended by @WilcoFiers and more accessibility tests will be done, before coming up  for a fix to #1170.

**Comment by WilcoFiers** [comment]
Need to do research on when iframes actually get identified by AT and when they do not. See comment here:

https://github.com/act-rules/act-rules.github.io/pull/1269/files#r413668324

**Comment by WilcoFiers** [comment]
@daniel-montalvo well do testing with JAWS and NVDA.

**Comment by WilcoFiers** [comment]
Test data available here: https://github.com/act-rules/act-rules.github.io/pull/1269/files#r421370248

**Comment by jkodu** [comment]
@WilcoFiers have a PR aiming to solve for above - https://github.com/act-rules/act-rules.github.io/pull/1322

**Comment by maryjom** [comment]
@WilcoFiers What's happening with this one? Is it ready to survey again, or is the CG still working on comments?
