### ISSUE TITLE
Resolve "Image filename is accessible name for image" feedback

### ISSUE THREAD

**Issue by tbostic32** [w3c/wcag-act#447]
[Survey Results](https://www.w3.org/2002/09/wbs/93339/RuleImageFilename/results)
[April 9 Meeting Minutes](https://www.w3.org/2020/04/09-wcag-act-minutes.html)
[Rule](https://act-rules.github.io/rules/9eb3f6)

# Rule Review: Image Filename is Accessible Name for Image
Related issues (compiled from comments below):
- [Alt text with file extension shouldn't pass](https://github.com/act-rules/act-rules.github.io/issues/1246)
- [Consider srcset/ picture + source](https://github.com/act-rules/act-rules.github.io/issues/1244)
- [Limit applicability](https://github.com/act-rules/act-rules.github.io/issues/465)

## Wilco Fiers
- [ ] The assumption is a little confusing to me. Would be good to make it a little clearer.
- [ ] https://github.com/act-rules/act-rules.github.io/issues/1244 Proposal to extend the rule to include srcset. Not a problem with the rule though.

## Jey Nandakumar
- [ ] https://github.com/act-rules/act-rules.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+9eb3f6+

## Charu Pandhi
- [ ] Not sure i understand why the language of the page is important to this rule
- [ ] How does the rule determine which file name is OK and which is not? Some filename makes sense, some definitely not. What about extensions in filenames? or any other nontext characters or numbers in filename.

## Kathy Eng
- [ ] Should the assumption include that the language of the filename matches the language of the page, not just that it can be determined? "Sufficiently understood" meaning it is a real word? Understood by whom?
- [ ] I think another failure example may be needed where "graph" is the image's filename and the accessible name, but it does not provide the image's equivalent purpose.
Example 1 - "https://www.w3.org/WAI/demos/bad/img/w3c" is the link, but isn't the image's filename is w3c.png?
- [ ] "Filename is valid accessible name" (9eb3f6) should limit its applicability #465" (https://github.com/act-rules/act-rules.github.io/issues/465).
- [ ] I'm not clear this rule is necessary. Wouldn't a rule for "Image has an accessible name that describes its purpose" broadly cover what's tested here?
A filename with extension for accessible name would pass only when the image is used to represent the file and not the image displayed. Perhaps the rule should be "File extensions are included in accessible name for files available for download."

## Mary Jo Mueller
- [ ] Agree with others. Why is the language important for this test? The test cases don't seem to indicate that language is important to the test. Also...when speaking of language - programmatic language? Human language?

- [ ] I have same concerns as Charu on this. "Pass" of test cases should actually need more test. I think it's ok for a test to check that the file name used as the alt matches without loss of info, but should result in further test needed to check it is sufficient. I have often seen images that use their file name as alt but the name is completely meaningless - numbers and such. I don't think we should pass such files as meeting non-text alternatives requirements.

- [ ] On quick glance through the techniques, I haven't seen where a file name is considered suffficient. However, I do understand that there are some cases where it could be - like a UI that is showing a list of files and has an image to represent each of them (like in Box). Or an app that shows thumbnails of pictures someone uploads.

- [ ] David Macdonald's issue #1246, #1244 from Wilco, and #465 from Kasper should be resolved. These all reflect my concerns for this rule.

- [ ] I think the expectation is unfounded for this rule. It requires manual test to really know if the name of the file serves an equivalent purpose. A file name rarely is sufficient in my experience. I like Kathy's suggestion here to define the applicability of the scope of the rule so it isn't misconstrued to be more broadly applicable.

- [ ] I think some work needs to be done to scope the rule's applicability and when a use of a filename is appropriate and when it usually isn't.

## Trevor Bostic

- [ ] I agree with Kathy that the 'sufficiently understood' leaves the assumption open ended. I would prefer to remove it and have the assumption state only "The rule assumes that the language of each test target can be correctly determined (either programatically or by analyzing the content)." This definition feels more concrete to me.Otherwise, we should elaborate on the meaning of "sufficiently understood".

**Comment by tbostic32** [comment]
From the meeting notes, the current actions are undergoing:

> Charu Pandhi 
> - [ ] Not sure i understand why the language of the page is important to this rule
> - [ ]  How does the rule determine which file name is OK and which is not? Some filename makes sense, some definitely not. What about extensions in filenames? or any other nontext characters or numbers in filename.
Charu is working on an updated solution to clarify the description and address the concerns above.

>Kathy Eng
> I think another failure example may be needed where "graph" is the image's filename and the accessible name, but it does not provide the image's equivalent purpose.
Example 1 - "https://www.w3.org/WAI/demos/bad/img/w3c" is the link, but isn't the image's filename is w3c.png?

Wilco is working on creating this new example.

**Comment by Jym77** [comment]
I tried to resolve the feedbacks in https://github.com/act-rules/act-rules.github.io/pull/1284 (clarifying intend, improving examples) and https://github.com/act-rules/act-rules.github.io/pull/1285 (improving applicability).

**Foreword:** I've seen a lot of misunderstanding around this rule (starting with me) which indicates that it was probably very poorly written… Hopefully things are better now 😃 This rule is intended as a semi-automatic rule checking a subset of "image accessible name is descriptive". Several tools may use the image filename as alt-text if none is provided. This is very often incorrect. This rule pinpoints these cases (automatic applicability) for humans to check the correctness of the alt-text (manual expectation). Restricting the applicability makes it possible for tool vendors to use this check as part of their semi-automated suits and list all targets to their customers. While listing every single image on a web site and asking for correctness of alt-text is overwhelming, this rule directs the attention of the human reviewer to a manageable number of cases.

This rule does not intend to replace "image name is descriptive" (which should be written soon-ish); it is a semi-automated subset of it, aiming at pinpointing a common case of failure. This rule does not intend to automatically decide if the alt-text is descriptive; it is semi-automated and human eyes are still needed. This rule does not intend to automatically decide if and when file extensions should be part of the accessible name; this is not a very clear topic and the question is delegated to human eyes.

**Note:** due to the change in applicability and examples, most implementation data will be dismissed with these changes. We'll probably need to gather implementation data anew before resubmitting the rule 😢 

> * [Alt text with file extension shouldn't pass](https://github.com/act-rules/act-rules.github.io/issues/1246)

Looking at Patrick H. Lauke and Wilco Fiers comments, it looks like this issue isn't really one and doesn't need action. However, I'd like to have David MacDonald acknowledgement before closing it.

> * [Consider srcset/ picture + source](https://github.com/act-rules/act-rules.github.io/issues/1244)
> * [Limit applicability](https://github.com/act-rules/act-rules.github.io/issues/465)

Both are handled by https://github.com/act-rules/act-rules.github.io/pull/1285

> ## Wilco Fiers
> * [ ]  The assumption is a little confusing to me. Would be good to make it a little clearer.

Added a example in https://github.com/act-rules/act-rules.github.io/pull/1284 that illustrate why the language of the test target is important.
As a rule of thumb, any rule that deal with something being descriptive needs to know in which language it is supposed to be descriptive. This is even more true for very short text that can easily have different meanings in different languages.

> * [ ]  [act-rules/act-rules.github.io#1244](https://github.com/act-rules/act-rules.github.io/issues/1244) Proposal to extend the rule to include srcset. Not a problem with the rule though.

Handled by https://github.com/act-rules/act-rules.github.io/pull/1285

> 
> ## Jey Nandakumar
> * [ ]  https://github.com/act-rules/act-rules.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+9eb3f6+

One of the issue doesn't need action. Both other are handled by https://github.com/act-rules/act-rules.github.io/pull/1285

> ## Charu Pandhi
> * [ ]  Not sure i understand why the language of the page is important to this rule

https://github.com/act-rules/act-rules.github.io/pull/1284 adds an example to illustrate this.
As a rule of thumb, any rule that deal with something being descriptive needs to know in which language it is supposed to be descriptive. This is even more true for very short text that can easily have different meanings in different languages.

> * [ ]  How does the rule determine which file name is OK and which is not? Some filename makes sense, some definitely not. What about extensions in filenames? or any other nontext characters or numbers in filename.

Determining whether the accessible name is OK is delegated to human tester. This is a semi-automated rule. https://github.com/act-rules/act-rules.github.io/pull/1284 adds a note about the intend of the rule and rewrite most examples to (hopefully) make this more obvious.

> ## Kathy Eng
> * [ ]  Should the assumption include that the language of the filename matches the language of the page, not just that it can be determined? "Sufficiently understood" meaning it is a real word? Understood by whom?

https://github.com/act-rules/act-rules.github.io/pull/1284 removes the part about "sufficiently understood" as it seems to be creating more confusion that anything else.
Also, the assumption is about the language **of the test target**, i.e. the image; hence there is no need to assume it matches the language of the page.

> * [ ]  I think another failure example may be needed where "graph" is the image's filename and the accessible name, but it does not provide the image's equivalent purpose.

I am not sure I fully understand what this new example should be. In any case, https://github.com/act-rules/act-rules.github.io/pull/1284 rewrote almost all examples hopefully with better cases. Would this new example still be needed?

>   Example 1 - "https://www.w3.org/WAI/demos/bad/img/w3c" is the link, but isn't the image's filename is w3c.png?

https://github.com/act-rules/act-rules.github.io/pull/1284 has changed all the examples using local files.

> * [ ]  "Filename is valid accessible name" (9eb3f6) should limit its applicability #465" ([act-rules/act-rules.github.io#465](https://github.com/act-rules/act-rules.github.io/issues/465)).

Handled by https://github.com/act-rules/act-rules.github.io/pull/1285

> * [ ]  I'm not clear this rule is necessary. Wouldn't a rule for "Image has an accessible name that describes its purpose" broadly cover what's tested here?

Yes. And such a rule is planned.
However, such a rule would flag for review every single image on a website, which is not really manageable. This rule uses an heuristic (accessible name = filename) which occurs from time to time (mostly by tools that include images and where no other alt-text is provided); thus it can pinpoint a manageable amount of cases for human to look at and can typically be used by semi-automated accessibility checkers without overwhelming users.

>   A filename with extension for accessible name would pass only when the image is used to represent the file and not the image displayed. Perhaps the rule should be "File extensions are included in accessible name for files available for download."

The rule does not try to decide whether the extension is OK or not. All that is delegated to human tester. 

After discussion with @WilcoFiers we decided to keep the rule as it is for these reasons. This will not prevent the broader (manual) rule to be written (it is planned) nor a more specific rule about when file extensions are needed (nothing is planned for that).

> ## Mary Jo Mueller
> * [ ]  Agree with others. Why is the language important for this test? The test cases don't seem to indicate that language is important to the test. Also...when speaking of language - programmatic language? Human language?

https://github.com/act-rules/act-rules.github.io/pull/1284 adds an example to illustrate why the language is important.
As a rule of thumb, any rule that deal with something being descriptive needs to know in which language it is supposed to be descriptive. This is even more true for very short text that can easily have different meanings in different languages.

> * [ ]  I have same concerns as Charu on this. "Pass" of test cases should actually need more test. I think it's ok for a test to check that the file name used as the alt matches without loss of info, but should result in further test needed to check it is sufficient. I have often seen images that use their file name as alt but the name is completely meaningless - numbers and such. I don't think we should pass such files as meeting non-text alternatives requirements.

The check here is not whether "the file name used as the alt matches" but whether the accessible name is sufficient. It does require "more test" in the form of input from human (this is a semi-automated rule).

https://github.com/act-rules/act-rules.github.io/pull/1284 is also adding an example where the filename/accessible name is a checksum to illustrate the case you point here.

> * [ ]  On quick glance through the techniques, I haven't seen where a file name is considered suffficient. However, I do understand that there are some cases where it could be - like a UI that is showing a list of files and has an image to represent each of them (like in Box). Or an app that shows thumbnails of pictures someone uploads.

Whether the accessible name (=filename) is sufficient or not is left to the interpretation of the user. This is a semi-automated rule.

> * [ ]  David Macdonald's issue #1246, #1244 from Wilco, and #465 from Kasper should be resolved. These all reflect my concerns for this rule.

Wilco's and Kasper's issues are solved by https://github.com/act-rules/act-rules.github.io/pull/1285 David MacDonald's issue does not need action as far as I can tell.

> * [ ]  I think the expectation is unfounded for this rule. It requires manual test to really know if the name of the file serves an equivalent purpose. A file name rarely is sufficient in my experience. I like Kathy's suggestion here to define the applicability of the scope of the rule so it isn't misconstrued to be more broadly applicable.

Yes, the expectation is manual. This is a semi-automated rule.

> * [ ]  I think some work needs to be done to scope the rule's applicability and when a use of a filename is appropriate and when it usually isn't.

After discussing with @WilcoFiers we decided to keep this rule as it (although with broader applicability). This will not prevent another rule defining when the use of a filename is appropriate (nothing like that is currently planned).

> ## Trevor Bostic
> * [ ]  I agree with Kathy that the 'sufficiently understood' leaves the assumption open ended. I would prefer to remove it and have the assumption state only "The rule assumes that the language of each test target can be correctly determined (either programatically or by analyzing the content)." This definition feels more concrete to me.Otherwise, we should elaborate on the meaning of "sufficiently understood".

https://github.com/act-rules/act-rules.github.io/pull/1284 removes this part of the assumption.

**Comment by Jym77** [comment]
The rule has been updated according to feedback, see https://github.com/act-rules/act-rules.github.io/pull/1284 and https://github.com/act-rules/act-rules.github.io/pull/1285 for details.

The rule is now ready for another round of review.

**Comment by WilcoFiers** [comment]
Awaiting further implementations.
