### ISSUE TITLE
Wide Review Tracker

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag-act#566]
This is a meta issue to track wide review steps for the specification.
See [How to do wide review](https://www.w3.org/Guide/documentreview/#who_to_ask_for_review) for details.

- [ ] the groups listed in the WG's charter, especially those who manage dependencies
- [ ] the groups jointly responsible for a particular document (if any).
- the horizontal groups:
  - Accessibility
      - [ ] Work through <a rel="nofollow" class="external text" href="https://w3c.github.io/apa/fast/checklist.html">this questionnaire</a>
      - [ ] [APA open issue](https://github.com/w3c/a11y-request/issues/89)
      
  - Architecture
      - [ ] [TAG open issue](https://github.com/w3ctag/design-reviews/issues/977)
      - [ ] If you are developing javascript APIs you may also want to ask <a rel="nofollow" class="external text" href="mailto:public-script-coord@w3.org">public-script-coord@w3.org</a>, a technical discussion list shared by W3C and ECMA's TC 39
  - Internationalization
      - [ ] Read the <a rel="nofollow" class="external text" href="https://www.w3.org/International/review-request">Request a review</a> page
      - [ ] work through the <a rel="nofollow" class="external text" href="https://www.w3.org/International/i18n-drafts/techniques/shortchecklist">Short Checklist</a>
      - [ ] [I18N open issue](https://github.com/w3c/i18n-request/issues/239)
  - Privacy
      - [ ] Write a "Privacy Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>, <a rel="nofollow" class="external text" href="https://www.w3.org/TR/fingerprinting-guidance/">Mitigating Browser Fingerprinting in Web Specifications</a>, and <a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc6973.html">RFC6973</a>
      - [ ] [Privacy open issue](https://github.com/w3cping/privacy-request/issues/141)
  - Security
      - [ ] Write a "Security Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>
      - [ ] [Security open issue](https://github.com/w3c/security-request/issues/73)
- Other outreach (if applicable)
